Revert "Revert "Chore/renovate"" (#333)
* Revert "Revert "Chore/renovate""

* fix check results

diff --git a/.github/actions/mise-hook-env/action.yaml b/.github/actions/mise-hook-env/action.yaml
--- a/.github/actions/mise-hook-env/action.yaml
+++ b/.github/actions/mise-hook-env/action.yaml
@@ -6,5 +6,10 @@ runs:
   steps:
     - name: export
       run: ./export.sh
-      shell: bash
+      shell: bash -leo pipefail {0}
       working-directory: ${{ github.action_path }}
+
+    - name: check mise command
+      run: |
+        command -v mise || { echo "mise not found"; exit 1; }
+      shell: bash -leo pipefail {0}
